### ISSUE TITLE
Add analytics to the site through GTM

### ISSUE THREAD

**Issue by BigActual** [realbig/kwaske_lift_th_18#1]
PM'ing the details

**Comment by BigActual** [comment]
You have access to the Tag Manager account. the details are under Admin > Container Name > Install Google Tag Manager

**Comment by d4mation** [comment]
Looks like this has already been done? 

https://github.com/realbig/kwaske_lift_th_18/commit/d9587fdb35843cf67f855898a19016bb596fd6fd

I cannot get kwaskerentals.com to load on my end in order to check whether that change has been deployed or not, but looking at the GTM account there are changes to include Analytics which have not been published yet.

**Comment by BigActual** [comment]
Maybe, I'm going to take a look now. If you see that in the future, feel free to publish.
